#!/usr/bin/env bash

install_rvm()
{
    if [ ! -x ~/.rvm ]; then 
      bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
    fi
    source $HOME/.rvm/scripts/rvm
    cp ~/repositories/developwithpassion/devtools/shared/dotfiles/rvm/global.gems ~/.rvm/gemsets/
    rvm reload
    rvm get head
    rvm reload
}

install_rvm
