#!/usr/bin/env bash

install_some_rubies()
{
    source $HOME/.rvm/scripts/rvm
    rvm install ruby-1.9.3
    rvm install ruby-1.9.2
    rvm --default ruby-1.9.3
    rvm system
}

install_some_rubies
